backend:
  name: github
  repo: timelessworld/okta-timeless
  branch: master
  
media_folder: blog/assets
public_folder: assets
  
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: ŚCIEŻKA }
      - { name: date, label: DATA, widget: datetime }
      - { name: title, label: TYTUŁ }
      - { name: mainImage, label: ZDJĘCIE, widget: image}
      - { name: body, label: ARTYKUŁ, widget: markdown }
